# settings
baseurl: ""
url: "https://gionn.net"

# meta
title: gionn.net
author: Giovanni Toraldo
description: A blog abouth tech, programming and my personal life, alive and kicking from 2005.

# social links
twitter_username: gionn
github_username:  gionn
facebook_username: gionn
instagram_username: gionn_net
linkedin_username: giovannitoraldo
rss: rss

# integrations
google_analytics: UA-107557-13
disqus:
  shortname: gionn-blog

# others
paginate: 5
permalink: /:year/:month/:day/:title/
timezone: Europe/Rome
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
  - jemoji
  - jekyll-redirect-from
